/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        InterBold: ["InterBold"],
        InterSemiBold: ["InterSemiBold"],
        InterMedium: ["InterMedium"],
        'InstrumentSans': ["'Instrument Sans'", 'sans-serif'],
        'Inter': ["'Inter'", 'sans-serif'],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        'black': '#000000',
        'text-gray': '#868686',
        'light-gray': '#F5F5F5',
        'mute-gray': '#ADADAD',
        'for-color': '#C4D6FC',
        'against-color': '#E7C8F8',
        'for-text': '#23365E',
        'against-text': '#442A52',
        'grad-11': '#BED8FC',
        'grad-12': '#EAC6F8',
        'grad-13': '#C4BCFF',
        'grad-21': '#BEDEFC',
        'grad-22': '#C6CDF8',
        'grad-23': '#C8BCFF',
        'grad-31': '#FCE9BE',
        'grad-32': '#EAC6F8',
        'grad-33': '#C4BCFF',
        'grad-41': '#FCBEE9',
        'grad-42': '#C9C6F8',
        'grad-43': '#C4BCFF',
        'fgrad-2': '#FCE9BE',
        'fgrad-31': '#FCBEE9', 
        'fgrad-41': '#DBEFFF',
        'fgrad-42': '#DFE3FF',
        'fgrad-43': '#CFF8FF',
        'tgrad-1': '#FFEBDB',
        'tgrad-2': '#FFDFE0',
        'tgrad-3': '#FFCFE3'
      },
    },
  },
  plugins: [],
};
